### ISSUE TITLE
View the deceaced person or persons

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#11]
### Description

As next of kin, I want to see an overview of the deceased person or persons and select the correct one, so that I am sure that I am submitting DGM for the correct person.

### Additional Information

There is no component in studio/apps, that can achieve this today. Will require collaboration with both team-apps and designsystem. 

The label above the person picker also needs to be adjusted. It should not be visible when there is only one deceased. 

[Design one deceased](https://www.figma.com/file/f3FeSdA0yWgFlJq4AoTNTl/Konseptskisser?type=design&node-id=1384-65740&t=7lN9SATefWJFcdnp-4)
[Design multiple deceased](https://www.figma.com/file/f3FeSdA0yWgFlJq4AoTNTl/Konseptskisser?type=design&node-id=1384-65817&t=7lN9SATefWJFcdnp-4)

### Tasks

- [x] Arrange a meeting with apps for specifying the requirements for the new person picker component
- [ ] Altinn/app-frontend-react#1247
- [ ] Implement RadioPanel in design system. (Will link to external task in the future)?
- [ ] Adjust `RadioButton` in  design system to be able to change background to panel and give proper focus
- [x] #24 

### Acceptance Criterias
- In the case where there is exactly one deceased, the deceased should be pre-selected, and I should not be able to change anything.
- In the case of multiple deceased, I should be given the choice for which deceased person I would like to submit DGM.
