### ISSUE TITLE
Adjustments to form

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#121]
Adjustments to form before user tests:

## Tasks:

- [ ] Remove Statsforvalteren from skjematittel.
- [x] Date formats on birth date and death date for the deceased.
- [x] Add radiobutton to death municipality (do you know the municipality of death?)
- [x] Prefill municipality of burial for kistebegravelse.
- [x] Alert on relation is missing "Er din"
- [ ] Wipe testperson data
