### ISSUE TITLE
Update list of funeral agencies

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#123]
Oslo is out of the Pilot-test, and we need to remove the funeral agencies that only operate in this area. 

## Tasks:

- [ ] Remove funeral agencies that only operate in Oslo.
- [ ] Add funeral agencies that operate in any new area we define. 
- [ ] Remove any remnants of the test data from Bærum.

**Comment by OlaDGM** [comment]
Dont remove from Bærum until we've fixed new pilotarea
