### ISSUE TITLE
Use forelder instead of mor/far on PersonRelasjon

### ISSUE THREAD

**Issue by chrrust** [Altinn/digital-gravferd#125]
### Description

@AstridDigdir and @chrrust agreed that we use `forelder` instead of `mor`/`far`. The benefit this gives us is that we can derive the inverse relation mentioned in the section above. Because `forelder` is a "new" relation in the model, we would need to add `forelder` to the `PersonRelasjon` enum across the application. Due to `mor`/`far` already being used, implementing `forelder` should be implemented so they coexist meanwhile migrating to using only `forelder`. Once `forelder` is used in both `dgm-gravferden` and `dgm-ansvarlig`, the task will then be to remove `mor`/`far` from being used

The implementation will require a migration of the database. Follow the steps in `dgm-gravferden` readme for doing this.

### Additional Information

- [Dgm.Gravferden.Domain.PersonRelasjon](https://altinn.studio/repos/sfvt/dgm-gravferden/src/branch/master/src/Dgm.Gravferden.Domain/Enums/PersonRelasjon.cs)

### Tasks

**We want to do this in a non-breaking way**
To do this, the steps of implementation should happen in a specific order:
- [x] Implement `forelder` to be co-existing with `mor`/`far` enums. Test that they work the same
- [x] Deploy code that includes `forelder`
- [x] Migrate `dgm-ansvarlig` to use `forelder` instead of `mor`/`far`
- [x] Test that the system is fully functional using only `forelder`
- [x] Remove redundant use of `mor`/`far` now that `forelder` is used

### Acceptance Criterias

- `Forelder` should be in use instead of `mor`/`far` on the `PersonRelasjon` enum
