### ISSUE TITLE
Format date of birth and date of death with date formatting

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#129]
### Description

For the deceased, when there are multiple deceased, the values for dates are not formatted by date. This is because groups do not support date dynamic expressions in the value field. We currently use a hidden datepicker with the `displayValue` function to format the date in correct, localized format.

### Tasks

- [ ] Add support for dynamic expressions in apps.
- [ ] Possibly add a `formatDate` function in dynamic expressions. 
- [ ] Update the view in ansvarlig with the the new values.
