### ISSUE TITLE
Implementere brukersignering av maskinlagde ansvarsmeldinger

### ISSUE THREAD

**Issue by chrrust** [Altinn/digital-gravferd#139]
### Description

I skrivende stund kan man maskinelt opprette nye ansvarsmeldinger via dgm-ansvarlig API, men brukeren som ansvarsmeldingen opprettes for kan foreløpig ikke "signere" disse og sende inn som bekreftelse.

Å løse dette avhenger av [applib-dotnet](https://github.com/Altinn/app-lib-dotnet) versjon 8 å bli gitt ut. Versjon 8 vil tillate oss å bruke _exclusive gateways_ i vår prosessflyt(les; `process.bpmn`). Dette er tilgjengelig i versjon 7 også, men i versjon 8 vil vi kunne tillate brukeren å gå tilbake og gjøre endringer i skjema før de sender inn. 

Koden for å opprette instansen på vegne av brukeren finnes i `StorageService.CreateInstanceAndPrefill()`. Det som mangler her er å legge til `await _processEngine.Next(processChangeContext);` etter å ha justert `process.bpmn` med exclusive gateway for en alternativ bekreftelsesside. 

Den alternative bekreftelsessiden vil også måtte lages. Det anbefales å ta i bruk multi-layout i stedet for single-layout. 

### Additional Information

dgm-ansvarlig:
- Eksisterende endepunkt: POST: `/statements-of-responsibility/:partyId`

Dokumentasjon:
- [Layout sets](https://docs.altinn.studio/app/development/configuration/process/customize/#custom-form-layout). Dette finnes og er klart i versjon 7.
- [Exclusive gateways](https://docs.altinn.studio/app/development/configuration/process/exclusive-gateways/#example-process-with-exclusive-gateways) - Dette vil være annerledes i v8. Da kan vi bruke expressions i `process.bpmn` 🦸 

### Tasks

- [ ] Konvertere til å bruke layout sets istedetfor single layout
- [ ] Implementere en tilpasset bekreftelsesside som kan brukes ved maskinell behandling
- [ ] Sette et flagg i datamodellen dersom instansen er maskinelt laget
- [ ] Utlede gateway-sti utifra flagget i punktet over. Bruke expressions til dette

**Comment by chrrust** [comment]
@mikaelrss Lurer på om dette kanskje kan være to separate oppgaver. Backenden er blocked av påvente av v8 fra applib-dotnet, men tror frontend-en kan gjøres. Hva tror du?

**Comment by mikaelrss** [comment]
Det er ikke helt klart for meg hva det er som skal legges i en egen layoutset i frontenden? 
Tenker vi at hele oppsummeringssiden skal bli en del av "bekreft"-steget som i dag? I så fall, vil v8 av app-lib-dotnet støtte at vi gjør endringer i datamodellene fra det steget?
