### ISSUE TITLE
Retrieving gravferder that the user is eligible to take responsibility for

### ISSUE THREAD

**Issue by thechrrust** [Altinn/digital-gravferd#41]
### Description

When the user enters the form in `dgm-ansvarlig` they should be presented with a list of gravferder that they are eligible to take responsibility for. This information is prefilled for the user, and the information exists in `dgm-gravferden` app. The task is to give the user this information when they enter the form.

To authorize the communication from `dgm-ansvarlig` to `dgm-gravferden` we need a setup in maskinporten. We would need a new scope like `altinn:dgm:internal` or so that we would request from dgm-ansvarlig that would be validated and accepted in dgm-gravferden. As part of this issue, we should also investigate this closer.

### Tasks

`dgm-gravferden`
- [x] New endpoint for the retrieval
- [x] Implement the reverse search logic in the `GravferdenRepository`
- [x] Authorization

`dgm-ansvarlig`
- [x] API client for calling dgm-gravferden
- [x] Prefill instance in dgm-ansvarlig with the gravferder the person can take responsibility for
- [x] Authorization

### Acceptance Criterias

The user is presented with a list of gravferder they are eligible to take responsibility for when they start the form
