### ISSUE TITLE
As a user I want to select whether there should be a burial or cremation

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#47]
### Description

I want to be able to select the form of the funeral (burial or cremation). 

### Additional Information

[Sketches for burial](https://www.figma.com/file/f3FeSdA0yWgFlJq4AoTNTl/Konseptskisser?type=design&node-id=1384-72483&mode=design&t=qQhAiLJxFHcTGJey-4)

[Sketches for cremation](https://www.figma.com/file/f3FeSdA0yWgFlJq4AoTNTl/Konseptskisser?type=design&node-id=1433-67204&mode=design&t=qQhAiLJxFHcTGJey-4)

### Tasks

- [ ] Show options for burial when burial is selected.
- [ ] Add warning for burial outside municipality where the deceased lived.
- [ ] Show options for cremation when cremation is selected.
- [ ] Add warning for burial of urn outside municipality where the deceased lived.
