### ISSUE TITLE
Add list component for funeral agencies

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#51]
### Description

Add a list component and an input field which will be the basis for searching for a funeral agency. 

### Additional Information

[Sketches](https://www.figma.com/file/f3FeSdA0yWgFlJq4AoTNTl/Konseptskisser?type=design&node-id=4353-99718&mode=design&t=elksctdJg5M3zCtt-4)

### Tasks

- [x] Add input field
- [x] Add list component
- [ ] Populate list component based on search
