### ISSUE TITLE
Cleanup contact info page

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#57]
### Description

Style the contact-info components to look like the other person Components. 

### Tasks

- [ ] Add stylesheet with person class
- [ ] Style contact-info
- [ ] Refactor people picker to use new class
