### ISSUE TITLE
Event for dgm-ansvarlig form submit

### ISSUE THREAD

**Issue by thechrrust** [Altinn/digital-gravferd#65]
### Description

On submitting the dgm-ansvarlig form, an event with the necessary data should be published to Altinn Events.
See [dgm-events](https://altinn.studio/repos/ttd/dgm-events/src/commit/e3491ee1364b5cbfe091d957a11329c720d87142/src/Digdir.Dgm.Events/Services/AltinnEventService.cs#L28) on how to publish generic events. It also does [some setup](https://altinn.studio/repos/ttd/dgm-events/src/commit/e3491ee1364b5cbfe091d957a11329c720d87142/src/Digdir.Dgm.Events/ConfigureServices.cs#L37) and has [some settings](https://altinn.studio/repos/ttd/dgm-events/src/commit/e3491ee1364b5cbfe091d957a11329c720d87142/App/appsettings.json#L27)

The dgm-gravferden API should implement an EventProcessor to handle this event. Take a look at [PersonIsDeadEventProcessor](https://altinn.studio/repos/ttd/dgm-gravferden/src/branch/master/App/Events/Processors/PersonIsDeadEventProcessor.cs) and the [readme](https://altinn.studio/repos/ttd/dgm-gravferden/src/branch/master/readme.md#adding-a-new-event-processor) for how to create a new EventProcessor.

The event processor should add the ansvarsmelding to the gravferd the person is trying to take responsibility for.

A new subscription needs to be created with Altinn Events. An example of a subscription is as follows:
`POST: https://platform.tt02.altinn.no/events/api/v1/subscriptions`
Request Body:
```json
{
  "endpoint": "https://ttd.apps.tt02.altinn.no/ttd/dgm-gravferden/api/Events/process",
  "typeFilter": "no.dgm.v1.responsible-form-submitted",
  "resourceFilter": "urn:altinn:resource:hendelser.dgm.api"
}
```

It can be useful to use webhook.site as the endpoint instead of the app gravferden app to begin with.

### Tasks

- [ ] Publish event from dgm-ansvarlig with the ansvarsmelding when the users submits the form
- [ ] Setup a subscription for Altinn Events with a webhook.site endpoint for testing. Verify it works when dgm-ansvarlig is deployed
- [ ] Create a new EventProcessor in dgm-gravferden
- [ ] Test the event processor locally using Postman or such
- [ ] Deploy and test end-to-end
