### ISSUE TITLE
Move from ttd to Statsforvalteren i Vestfold og Telemark

### ISSUE THREAD

**Issue by chrrust** [Altinn/digital-gravferd#79]
### Description

The projects in DGM resides in the wrong org. It needs to be moved to SFVT from ttd

### Tasks

- [x] new key vault
- [x] dgm-gravferden
- [x] dgm-ansvarlig
- [x] dgm-events
- [x] deploy and verify dgm-ansvarlig
- [x] deploy and verify dgm-gravferden
- [x] deploy and verify dgm-events

**Comment by thechrrust** [comment]
Blocked while waiting for maskinporten to be available to SFVT

**Comment by chrrust** [comment]
This is now working using a combination of ttd and sfvt
